#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2026 Hugh Walsh
#
# SPDX-License-Identifier: MIT

# This file: scripts/py_lock.sh

# Write constraints.txt: the exact version of every Python package (direct and
# indirect) installed in the abe virtual environment.
#
# Run this only after verifying an environment (regressions, formal, static
# checks, uarch tools). `make py-install-*` installs with `-c constraints.txt`,
# so a fresh clone gets exactly the verified versions. pip and abe itself are
# left out: pip is upgraded separately and abe is installed from the checkout.
#
# Usage: py_lock.sh [python] [output]
#   python: interpreter of the abe virtual environment (default: .venv/bin/python)
#   output: file to write (default: constraints.txt)

set -eu

cd "$(dirname "$0")/.." || exit 1
PYTHON=${1:-.venv/bin/python}
OUT=${2:-constraints.txt}

if [ ! -x "$PYTHON" ]; then
    echo "ERROR: $PYTHON not found. Run: make py-venv-all && make py-install-all" >&2
    exit 2
fi

PY_VER=$("$PYTHON" -c 'import platform; print(platform.python_version())')
TMP="$OUT.tmp"

{
    cat <<EOF
# SPDX-FileCopyrightText: 2026 Hugh Walsh
#
# SPDX-License-Identifier: MIT

# This file: $OUT

# Exact versions of every Python package verified with ABE, direct and indirect.
# Generated by \`make py-lock\` from a verified .venv; do not edit by hand.
# \`make py-install-*\` installs with \`pip install -c $OUT\`, so a fresh clone
# gets the verified environment. See docs/python_dev.md.
#
# Verified with Python $PY_VER on $(uname -sm).

EOF
    "$PYTHON" -m pip freeze --exclude-editable --exclude pip --exclude abe
} >"$TMP"

mv "$TMP" "$OUT"
echo "Wrote $OUT ($(grep -c '==' "$OUT") packages, Python $PY_VER)"
